# Configuration file for YREC test suite

[paths]

# Location of YREC executable to test
yrec = src/yrec

# Test input locations
# Entries in this list may be directories where nml1,nml2 pairs are found.
# All corresponding nml1,nml2 pairs will be collected as test cases and
# run.
#
# A comma-separated list of
#   directory, nm1-file, nml2-file
# may also be used to define a single test case. e.g.
#   examples/run_from_dbl_to_zams, Test_m0050_feh0_noGS_ZAMS.nml1, run_from_dbl_to_zams.nml2
tests =
    testsuite
    examples/giant_differential_rotation
    examples/run_from_dbl_to_zams
    examples/run_from_seed_to_start
    examples/run_from_start_to_dbl
    examples/run_from_zahb_to_tahb
    examples/run_rotation_to_RG
    examples/run_standard_solar_model
    examples/test_nuclear_reaction_rates
    #testsuite, Test_m9p0feh+0p0GS98_base_TAHB.nml1, Test_m9p0feh+0p0GS98_base_TAHB.nml2 
    #examples/run_from_zahb_to_tahb, Solar_m1p0feh+0p0_GN93_MESA_TAHB.nml1, Solar_m1p0feh+0p0_GN93_MESA_TAHB.nml2
    #examples/giant_differential_rotation


# Subdirectory of each test directory which will hold test reference outputs
# used for comparison of future runs.
reference_dir = standard

[options]
show_output_upon_failure = True

# Control whether or not differences in the version values stored in output
# file headers will cause a comparison with a reference standard output to
# fail.
# If True, differences in application version (e.g. v202602) or commit hash
# (4ede684) or (4ede684-dirty) will be ignored to cut down on extraneous noise
# during development testing.
ignore_version_diffs = True

[tolerances]
float_frac_tol = 0.02
int_abs_tol    = 0
