C
C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C INTEGRATOR FOR 2 ZONE KAWALER WIND MODEL
C BASED ON BSSTEP FROM NUMERICAL RECIPES
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
       SUBROUTINE INT2ZONE(SAGE,SI,SIE,SIC,STAUCZ,FCZ,FSTRUCT,YI,YIE,
     *                     YCZ,YSTR,YTAU,SJC0,SJE0,SJC1,SJE1,I,J,T0,DTT,
     *                     EXCEN,EXW,FCEN,FK2,YCEN,LOK,LOSS)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      PARAMETER(NTRACK=40,NMOD=20000,NMAX=15)
      PARAMETER (ONE=1.0D0,SHRINK=0.95D0,GROW=1.2D0)
C USER PARAMETERS, WIND LAW
      COMMON/PARAM/LSOLID,IWIND,PMMA,PMMB,PMMC,PMMM,SOLJDOT,SOLMDOT,FK,
     *             PDISK,TDISK,TAUCOUPLE,WCRIT,LROSS
C SOLAR UNITS IN CGS, USED FOR LOSS LAW
C SOLAR MASS, RADIUS, LUMINOSITY, SURFACE P, OVERTURN TIMESCALE (CGS),
C ANGULAR VELOCITY(RAD/S)
      COMMON/SOLAR/ SOLM,SOLR,SOLL,SOLP,SOLTAU,SOLW
C PHYSICAL CONSTANTS
C G (CGS), 2/3, SECONDS IN YEAR, SECONDS IN DAY
      COMMON/CONST/CG,CC23,CPI,CSECYR,CSECDAY
      INTEGER*4 NSEQ(11),IMAX,NUSE
C INPUTS FROM TRACKS - CGS OR SOLAR UNITS AS NOTED
C SAGE = AGE (YR), SL = L/LSUN SR = R/RSUN SM = M/MSUN
C SRCZ = R OF CZ BASE (CGS) SMCZ = MASS OF SURFACE CZ, MSUN
C SI, SIE, SIC = CGS MOMENT OF INERTIA TOTAL, CORE, ENVELOPE
C STAUCZ = CONVECTIVE OVERTURN TIMESCALE (SEC), SP = ATM PRESSURE TAU=2/3
C SXC = CENTRAL X SHEC= POST-MS HE CORE MASS (MSUN), BOTH USED FOR ISOCHRONES
      REAL*8 SAGE(NTRACK,NMOD),FSTRUCT(NTRACK,NMOD),
     * SI(NTRACK,NMOD),STAUCZ(NTRACK,NMOD),FCZ(NTRACK,NMOD),FK2,
     * SIC(NTRACK,NMOD),SIE(NTRACK,NMOD),EXCEN,EXW,FCEN(NTRACK,NMOD)
C SPLINE INTERPOLATION VECTORS
      REAL*8 YI(NMOD),YSTR(NMOD),YTAU(NMOD),YIE(NMOD),YCZ(NMOD),
     *       YCEN(NMOD)
C SCALARS
      REAL*8 SJE0,SJE1,T0,DTT,T1,H,HH,H1,A,B,SI1,SSTR1,STAU1,SWE1,SWE0,
     *       SJC0,SJC1,SSTR0,SWC0,SWC1,SJCSAV,SJESAV,STAU0
      REAL*8 YEST(NMAX),YOUT(NMAX),YERR(NMAX),YTEST(2,11),YSCAL(NMAX),
     *        ERR(NMAX),DJCOUP0,DJCOUP1,DJDT0,DJDT1,W0,W1
      CHARACTER*8 FORMAT1
      LOGICAL*4 LOK,LOSS
C OUTPUT VECTORS - CGS UNITS
C SWE = OMEGA(ENV), SWC = OMEGA(CORE), SJ= TOTAL J SJE = ENVELOPE J
C SJC = CORE J SPROT = SURFACE PERIOD (DAYS)
      DATA NSEQ /2,4,6,8,12,16,24,32,48,64,96/
      DATA EPS,IMAX,NUSE/1.0D-4,11,7/
      SAVE
C CONVERGENCE FLAG
      LOK = .FALSE.
C SCALE ERROR IN TRANSPORT TERM BY ENVELOPE J
      YSCAL(1) = SJE0
C TAU(CZ) CAN OSCILLATE WHEN CLOSE TO A FULLY CONVECTIVE STATE
C TO AVOID NUMERICAL PATHOLOGIES, RESTRICT THE RANGE TO WITHIN
C THE ENDPOINT VALUES.
      STAUMIN = MIN(STAUCZ(I,J-1),STAUCZ(I,J))
      STAUMAX = MAX(STAUCZ(I,J-1),STAUCZ(I,J))
C SCALE ERROR IN LOSS RATE BY INITIAL LOSS RATE
      WTEST = SJE0/SIE(I,J-1)
      IF(LROSS)THEN
         W0 = WTEST*STAUMIN/SOLTAU
      ELSE
         W0 = WTEST
      ENDIF
      YSCAL(2) = FSTRUCT(I,J-1)*WTEST*MIN(W0,WCRIT)**(EXW-1.0D0)
      DO KK = 1, 11
         YTEST(1,KK) = 0.0D0
         YTEST(2,KK) = 0.0D0
      END DO
20    CONTINUE
C CONVERT COUPLING TIMESCALE FROM YR TO GYR
      TCOUPLE = 1.0D-9*TAUCOUPLE
      DJCOUP0 = 0.0D0
      DJCOUP1 = 0.0D0
C STORE STARTIN ANGULAR MOMENTA
      SJCSAV = SJC0
      SJESAV = SJE0
      DO II = 1,IMAX
         SJC0 = SJCSAV
         SJE0 = SJESAV
         H1 = DTT/FLOAT(NSEQ(II))
         T1 = T0
         SJ1 = SJ0
         HH = SAGE(I,J)-SAGE(I,J-1)
C INTERPOLATE BETWEEN POINTS J AND J-1 FOR STRUCTURE VARIABLES
         A = (SAGE(I,J)-T0)/HH
         B = (T0-SAGE(I,J-1))/HH
C TOTAL MOMENT OF INERTIA I
         SI0 = A*SI(I,J-1)+B*SI(I,J)+
     *   ((A**3-A)*YI(J-1)+(B**3-B)*YI(J))*(HH**2)/6.0D0
C ENVELOPE MOMENT OF INERTIA IE
         SIE0 = A*SIE(I,J-1)+B*SIE(I,J)+
     *   ((A**3-A)*YIE(J-1)+(B**3-B)*YIE(J))*(HH**2)/6.0D0
C CORE MOMENT OF INERTIA = DIFFERENCE BETWEEN TOTAL AND ENVELOPE
         SIC0 = SI0 - SIE0
C CONSTANT AND STRUCTURAL TERMS IN THE LOSS PRESCRIPTION HERE
         SSTR0 = A*FSTRUCT(I,J-1)+B*FSTRUCT(I,J)+
     *   ((A**3-A)*YSTR(J-1)+(B**3-B)*YSTR(J))*(HH**2)/6.0D0            
C CENTRIFUGAL TERM
         SCEN0 = A*FCEN(I,J-1)+B*FCEN(I,J)+
     *   ((A**3-A)*YCEN(J-1)+(B**3-B)*YCEN(J))*(HH**2)/6.0D0            
C 2/3 RADIUS OF CZ BASE ^2 * DM/DT
         SRCZ0 = A*FCZ(I,J-1)+B*FCZ(I,J)+
     *   ((A**3-A)*YCZ(J-1)+(B**3-B)*YCZ(J))*(HH**2)/6.0D0
C SURFACE AND CORE ANGULAR VELOCITIES
C ENVELOPE I SHOULD NEVER BE ZERO, STOP IF TRUE
         IF(SIE0.LE.0.0D0)THEN
            WRITE(*,101)SIE0,II,T1
 101        FORMAT('NEGATIVE OR ZERO ENVELOPE I',E12.4,'MODEL',I5,
     *             'AGE(GYR)'E12.4)
            GOTO 999
         ENDIF
         SWE0 = SJE0/SIE0
C CONVECTIVE OVERTURN TIMESCALE
         IF(LROSS)THEN
            STAU0 = A*STAUCZ(I,J-1)+B*STAUCZ(I,J)+
     *   ((A**3-A)*YTAU(J-1)+(B**3-B)*YTAU(J))*(HH**2)/6.0D0            
            STAU0=MAX(STAU0,STAUMIN)
            STAU0=MIN(STAU0,STAUMAX)
            IF(IWIND.EQ.3)THEN
               W0 = SWE0*STAU0/SOLTAU
               WC0 = WCRIT
            ELSE IF(IWIND.EQ.2)THEN
               W0 = SWE0
               WC0 = WCRIT*SOLTAU/STAU0
            ENDIF
         ELSE
            W0 = SWE0
            WC0 = WCRIT
         ENDIF
C CORE I CAN START AS ZERO,INITIALIZE WITH ENVELOPE OMEGA IF TRUE
         IF(SIC0.LE.0.0D0)THEN
            SWC0 = SWE0
         ELSE
            SWC0 = SJC0/SIC0
         ENDIF
C COUNTER TO SUM ANGULAR MOMENTUM LOSS OVERALL
         SUMDJ = 0.0D0
         SUMTRAN = 0.0D0
         DO JJ = 1,NSEQ(II)
            T1 = T1 + H1
C INTERPOLATE BETWEEN POINTS J AND J-1 FOR STRUCTURE VARIABLES
            A = (SAGE(I,J)-T1)/HH
            B = (T1-SAGE(I,J-1))/HH
C TOTAL MOMENT OF INERTIA I
            SI1 = A*SI(I,J-1)+B*SI(I,J)+
     *      ((A**3-A)*YI(J-1)+(B**3-B)*YI(J))*(HH**2)/6.0D0
C ENVELOPE MOMENT OF INERTIA IE
            SIE1 = A*SIE(I,J-1)+B*SIE(I,J)+
     *      ((A**3-A)*YIE(J-1)+(B**3-B)*YIE(J))*(HH**2)/6.0D0
C CORE MOMENT OF INERTIA = DIFFERENCE BETWEEN TOTAL AND ENVELOPE
            SIC1 = SI1 - SIE1
C ALTHOUGH THE STARTING CORE I CAN BE ZERO, IT SHOULD BE NONZERO
C AT INTERMEDIATE TIMES
            IF(SIC1.LE.0.0D0)THEN
C SWITCH TO LINEAR INTERPOLATION IN MOMENT OF INERTIA
               SI1 = SI(I,J-1)+B*(SI(I,J)-SI(I,J-1)) 
               SIE1 = SIE(I,J-1)+B*(SIE(I,J)-SIE(I,J-1)) 
               SIC1 = SI1 - SIE1
               IF(SIC1.LE.0.0D0)THEN
                  WRITE(*,411)I,J,SI(I,J-1),SI(I,J),SIE(I,J-1),
     *                 SIE(I,J),SI1,SIE1,SIC1
 411              FORMAT(' NEGATIVE CORE I RUN STOPPED',2I5,1P7E12.4)
                  GOTO 999
               ELSE
                  WRITE(*,412)I,J,SI(I,J-1),SI(I,J),SIE(I,J-1),
     *                 SIE(I,J),SI1,SIE1,SIC1
 412              FORMAT(' NEGATIVE CORE I-SWITCHED TO LINEAR',2I5,1P7E12.4)
               ENDIF
            ENDIF
C CONSTANT AND STRUCTURAL TERMS IN THE LOSS PRESCRIPTION HERE
            SSTR1 = A*FSTRUCT(I,J-1)+B*FSTRUCT(I,J)+
     *      ((A**3-A)*YSTR(J-1)+(B**3-B)*YSTR(J))*(HH**2)/6.0D0            
C CENTRIFUGAL TERM
            SCEN1 = A*FCEN(I,J-1)+B*FCEN(I,J)+
     *      ((A**3-A)*YCEN(J-1)+(B**3-B)*YCEN(J))*(HH**2)/6.0D0            
C RADIUS OF CZ BASE, CM
            SRCZ1 = A*FCZ(I,J-1)+B*FCZ(I,J)+
     *      ((A**3-A)*YCZ(J-1)+(B**3-B)*YCZ(J))*(HH**2)/6.0D0
C START OF STEP DJ/DT
            FCC0 = MIN(0.5D0,SWE0**2*SCEN0)
            FC0 = (FK2/(FK2**2+FCC0)**0.5D0)**EXCEN
            IF(LOSS)THEN
               DJDT0 = -FC0*SSTR0*SWE0*MIN(W0,WC0)**(EXW-1.0D0)
            ELSE
               DJDT0 = 0.0D0
            ENDIF
C START OF STEP ESTIMATE FOR MOMENT OF INERTIA OF MASS 
C EXCHANGED BETWEEN ENVELOPE AND CORE
C TWO BRANCHES: CORE GROWS (SURFACE OMEGA FOR MATERIAL TO CORE) 
C OR CORE SHRINKS (CORE OMEGA FOR MATERIAL TO CZ)
            IF(SRCZ0.LT.0.0D0)THEN
C SHRINKING ENVELOPE; J+I ADDED TO CORE
               DJTRAN0 = SRCZ0*H1*SWE0
            ELSE
C GROWING ENVELOPE - ANGULAR MOMENTUM LOST FROM CORE
C COPY END OF STEP VALUES TO START OF NEXT STEP VALUES
               DJTRAN0 = SRCZ0*H1*SWC0
            ENDIF
            IF(TCOUPLE.GT.0.0D0)THEN
               DJCOUP0 = SIE0*SIC0/SI0*(SWC0-SWE0)/TCOUPLE
            ENDIF
C TRIAL CORRECTED ESTIMATE FOR END OF STEP DJ/DT
C INCLUDES BOTH LOSS AND CORRECTION FOR CHANGE IN I
            SWE1 = (SJE0 + DJTRAN0 +H1*(DJCOUP0 - DJDT0))/SIE1
            IF(SWE1.LT.0.0D0)THEN
               WRITE(*,102)SWE1,II,T1
 102           FORMAT('NEGATIVE ENVELOPE OMEGA',E12.4,'MODEL',I5,
     *             'AGE(GYR)'E12.4)
               GOTO 999
            ENDIF
C CONVECTIVE OVERTURN TIMESCALE
            IF(LROSS)THEN
               STAU1 = A*STAUCZ(I,J-1)+B*STAUCZ(I,J)+
     *      ((A**3-A)*YTAU(J-1)+(B**3-B)*YTAU(J))*(HH**2)/6.0D0            
               STAU1=MAX(STAU1,STAUMIN)
               STAU1=MIN(STAU1,STAUMAX)
               IF(IWIND.EQ.3) THEN
                  W1 = SWE1*STAU1/SOLTAU
                  WC1 = WCRIT
               ELSE IF(IWIND.EQ.2)THEN
                  W1 = SWE1
                  WC1 = WCRIT*SOLTAU/STAU1
               ENDIF
            ELSE
               W1 = SWE1
               WC1 = WCRIT
            ENDIF
            FCC1 = MIN(0.5D0,SWE1**2*SCEN1)
            FC1 = (FK2/(FK2**2+FCC1)**0.5D0)**EXCEN
            SWC1 = (SJC0 - DJTRAN0 - H1*DJCOUP0)/SIC1
            IF(SWC1.LT.0.0D0)THEN
               WRITE(*,103)SWC1,II,T1
 103           FORMAT('NEGATIVE CORE OMEGA',E12.4,'MODEL',I5,
     *             'AGE(GYR)'E12.4)
               GOTO 999
            ENDIF
C UPDATE EXCHANGE TERM (END OF TIMESTEP VALUE)
            IF(SRCZ0.LT.0.0D0)THEN
               DJTRAN1 = SRCZ1*H1*SWE1
            ELSE
               DJTRAN1 = SRCZ1*H1*SWC1
            ENDIF
            IF(TCOUPLE.GT.0.0D0)THEN
               DJCOUP1 = SIE1*SIC1/SI1*(SWC1-SWE1)/TCOUPLE
            ENDIF
C UPDATE TORQUE ESTIMATE (END OF TIMESTEP VALUE)
            IF(LOSS)THEN
               DJDT1 = -FC1*SSTR1*SWE1*MIN(W1,WC1)**(EXW-1.0D0)
            ELSE
               DJDT1 = 0.0D0
            ENDIF
            SJE1=SJE0+0.5D0*(H1*(DJDT0+DJDT1 +
     *           DJCOUP0+DJCOUP1)+DJTRAN0+DJTRAN1)
            SWE1 = SJE1/SIE1
            SJC1 = SJC0 - 0.5D0*(DJTRAN0+DJTRAN11)
            SWC1 = SJC1/SIC1
            IF(SWE1.LT.0.0D0)THEN
                D0 = H1*DJDT0
                D1 = H1*DJDT1
                WRITE(*,44)I,J,T0,DTT,SWE0,SWE1,SJE0,SJE1,DJTRAN0,
     *          DJTRAN1,D0,D1,SIE0,SIE1
 44         FORMAT('NEGATIVE ENVELOPE OMEGA',2I5,1P6E12.4/1P6E12.4)
                GOTO 999
            ENDIF
            IF(SWC1.LT.0.0D0)THEN
               WRITE(*,103)SWC1,II,T1
               GOTO 999
            ENDIF
            SUMDJ = SUMDJ + 0.5D0*H1*(DJDT0+DJDT1)
            SUMTRAN = SUMTRAN + 0.5D0*(DJTRAN0+DJTRAN1)+
     *                0.5D0*H1*(DJCOUP0+DJCOUP1)
C            WRITE(*,55)I,J,SUMDJ,H1,DJDT0,DJDT1
C 55         FORMAT(2I5,1P4E12.4)
            SI0 = SI1
            SIE0 = SIE1
            SIC0 = SIC1
            SSTR0 = SSTR1
            SCEN0 = SCEN1
            STAU0 = STAU1
            W0 = W1
            SRCZ0 = SRCZ1
            SWE0 = SWE1
            SWC0 = SWC1
            SJE0 = SJE1 
            SJC0 = SJC1
         END DO
	 XEST = (DTT/FLOAT(NSEQ(II)))**2
         NV = 2
         YEST(1) = SUMTRAN
         YEST(2) = SUMDJ
	 CALL RATEXT(II,XEST,YEST,YOUT,YERR,NV,NUSE)
	 ERRMAX = 0.0D0
         DO KK = 1,NV
            ERRMAX = DMAX1(ERRMAX,DABS(YERR(KK)/YSCAL(KK)))
	    ERR(KK) = DABS(YERR(KK)/YSCAL(KK))
         END DO
	 ERRMAX = ERRMAX/EPS
         YTEST(1,II) = YOUT(1)
         YTEST(2,II) = YOUT(2)
	 IF(ERRMAX.LT.ONE) THEN
            SJC0 = SJCSAV
            SJE0 = SJESAV
            SJE1 = SJE0 + YOUT(1) + YOUT(2)
C COMPUTE TRANSFER OF ANGULAR MOMENTUM FROM CORE TO ENVELOPE
            SJC1 = SJC0 - YOUT(1)
            III = MIN(9,II)
            WRITE(FORMAT1,'(A1,I0,A6)')'(',III,'E12.4)'
C            WRITE(55,901)II,T1
C 901  FORMAT('NUMBER OF INTERATIONS',I5,' AGE ',1PE12.4)
C            WRITE(55,FORMAT1)(YTEST(1,KK),KK=1,II)
C            WRITE(55,FORMAT1)(YTEST(2,KK),KK=1,II)
C            WRITE(55,913)SJC0,SJC1,SJE0,SJE1,SWC0,SWC1,SWE0,SWE1,
C     *      DJDT0,DJDT1,DJTRAN0,DJTRAN1,DJCOUP0,DJCOUP1
C 913        FORMAT(1P14E12.4)
            LOK = .TRUE.
	    RETURN
	 ENDIF
      END DO
C      H = 0.25D0*H/2.0D0**INT((IMAX-NUSE)/2)
C      H = 0.25D0*H/2**((IMAX-NUSE)/2)
C      IF(X+H.EQ.X) THEN
C         WRITE(*,*) 'ERROR IN BSSTEP'
C	 STOP
C      END IF
C      GOTO 20
      WRITE(*,902)II,T1
      WRITE(*,FORMAT1)(YTEST(1,KK),KK=1,II)
      WRITE(*,FORMAT1)(YTEST(2,KK),KK=1,II)
 902  FORMAT('FAILED TO CONVERGE IN INT2ZONE. ITERATIONS',I5,' AGE ',1PE12.4)
 999  CONTINUE
      LOK = .FALSE.
      RETURN
      END
