C MHP 3/12 Program for angular momentum evolution of low mass stars.
C The underlying angular momentum evolution model involves the following
C assumptions: 1) Rigid rotation in convective regions;
C 2) Star-disk coupling in the protostellar domain.  Parameters:
C Rotating held fixed at period PDISK (days) for time TDISK (Myr).
C If TDISK = 0 PDISK is the starting rotation period
C 3) Solid Body rotation enforced if LSOLID = T
C 4) Core-Envelope decoupling modeled the same as Denissenkov et al. 2010:
C Parameter TAUCOUPLE, define DJ = (Ic-Ie)/(Ic+Ie)*(Wc-We); then
C d Jc/dt = -DJ/TAUCOUPLE + 2/3Rcz^2 We DMcz (DM cz= change in mass of cz)
C d Je/dt = - d Jc/dt - JDOT (wind)
C Angular momentum loss has four options.
C IWIND = 1 (no loss) IWIND = 2 (PMM12) IWIND = 3 (mod K88) IWIND = 4 RM11
C The program reads in multiple tracks and evolves them forward according
C To the specified physics.  The rotational evolution is then written out
C Along with isochrones at user-specified points.
      IMPLICIT REAL*8 (A-H, O-Z)
      IMPLICIT LOGICAL*4 (L)
C MAXIMUM NUMBER OF MASS TRACKS AND MODELS PER TRACK RESPECTIVELY
      PARAMETER(NTRACK=40,NMOD=20000)
C USER PARAMETERS, WIND LAW
C ADD CONSTANT J TO M OPTION
      COMMON/PARAM/LSOLID,IWIND,PMMA,PMMB,PMMC,PMMM,SOLJDOT,SOLMDOT,FK,
     *             PDISK,TDISK,TAUCOUPLE,WCRIT,LROSS,SJTOM,LJTOM
C SOLAR CALIBRATION OPTION
      COMMON/SOLCAL/SOLAGE,LCALSOL
C SOLAR UNITS IN CGS, USED FOR LOSS LAW
C SOLAR MASS, RADIUS, LUMINOSITY, SURFACE P, OVERTURN TIMESCALE (CGS),
C ANGULAR VELOCITY(RAD/S)
      COMMON/SOLAR/ SOLM,SOLR,SOLL,SOLP,SOLTAU,SOLW
C PHYSICAL CONSTANTS
C G (CGS), 2/3, SECONDS IN YEAR, SECONDS IN DAY
      COMMON/CONST/CG,CC23,CPI,CSECYR,CSECDAY
C INPUTS FROM TRACKS - CGS OR SOLAR UNITS AS NOTED
C SAGE = AGE (YR), SL = L/LSUN SR = R/RSUN SM = M/MSUN
C SRCZ = R OF CZ BASE (CGS) SMCZ = MASS OF SURFACE CZ, MSUN
C SI, SIE, SIC = CGS MOMENT OF INERTIA TOTAL, CORE, ENVELOPE
C STAUCZ = CONVECTIVE OVERTURN TIMESCALE (SEC), SP = ATM PRESSURE TAU=2/3
C SXC = CENTRAL X SHEC= POST-MS HE CORE MASS (MSUN), BOTH USED FOR ISOCHRONES
      REAL*8 SAGE(NTRACK,NMOD),SL(NTRACK,NMOD),SR(NTRACK,NMOD),
     * SM(NTRACK,NMOD),SRCZ(NTRACK,NMOD),SMCZ(NTRACK,NMOD),
     * SI(NTRACK,NMOD),SIE(NTRACK,NMOD),SIC(NTRACK,NMOD),
     * STAUCZ(NTRACK,NMOD),SP(NTRACK,NMOD),
     * SXC(NTRACK,NMOD),SHEC(NTRACK,NMOD),STEFF(NTRACK,NMOD)
C NM = VECTOR OF TRACK LENGTHS
      INTEGER*4 NM(NTRACK)
C MHP 6/19 ADDED OPTION TO SPECIFY A SPECIFIC J, RATHER THAN A PERIOD
      LOGICAL*4 LJTOM
C OUTPUT VECTORS - CGS UNITS
C SWE = OMEGA(ENV), SWC = OMEGA(CORE), SJ= TOTAL J SJE = ENVELOPE J
C SJC = CORE J SPROT = SURFACE PERIOD (DAYS)
      REAL*8 SWE(NTRACK,NMOD),SWC(NTRACK,NMOD),SJ(NTRACK,NMOD),
     * SJE(NTRACK,NMOD),SJC(NTRACK,NMOD),SPROT(NTRACK,NMOD)
      REAL*8 EXCEN,EXW,FSTRUCT(NTRACK,NMOD),FCZ(NTRACK,NMOD),
     *       FK2,FCEN(NTRACK,NMOD),FAC_CEN,B_BSOL,DMDT,BMAX,
     *       DMDTMAX
C PERMIT UP TO 40 ROTATION CASES, either in period or specific j
      REAL*8 TDISK0(40),PDISK0(40),SJ0(40)
      SAVE
c MHP 6/19 ADDED CONSTANT J TO M OPTION
      NAMELIST /CONTROL/
     *   INUMT,LSOLID,IWIND,FK,PMMA,PMMB,PMMC,PMMM,
     *   SOLJDOT,SOLMDOT,PDISK0,TDISK0,TAUCOUPLE,WCRIT,LROSS,
     *   LCALSOL,NUMROT,SOLW,SOLAGE,SJ0,LJTOM
C ADDED LJTOM, SJ0 TO INPUTS
      DATA INUMT,LSOLID,IWIND,FK,PMMA,PMMB,PMMC,PMMM,SOLJDOT,
     *   SOLMDOT,TAUCOUPLE,WCRIT,LROSS,LCALSOL,NUMROT,SOLW,
     *   SOLAGE,LJTOM/
     *   1,.TRUE.,1,2.46D0,2.0D0,1.0D0,0.0D0,0.22D0,
     *   1.3D30,1.27D12,2.0D7,3.0D-5,.TRUE.,.FALSE.,1,
     *   2.86307D-6,4.568D9,.FALSE./
C ADJUST NUMBER OF ENTRIE TO EQUAL NROT, THE MAXIMUM NUMBER OF
C ROTATION CASES CONSIDERED, WHICH IS ENTERED AS A PARAMETER
      DATA PDISK0/40*8.0D0/
      DATA TDISK0/40*3.0D0/
      DATA SJ0/40*2.0E16/
C SET UP CONSTANTS
C GRAVITATIONAL CONSTANT - NOTE VALUE IS THAT IN THE YREC CODE,
C MODERN VALUE IS SLIGHTLY DIFFERENT BUT WITHIN 1 SIGMA
      CG = 6.6725D-8
      CC23 = 2.0D0/3.0D0
C PI
      CPI = 3.1415926535898D0
C SECONDS IN DAY AND YEAR
      CSECDAY = 2.4D1*3.6D3
      CSECYR = 3.652425D2*CSECDAY
C SOLAR MASS, RADIUS, LUMINOSITY
      SOLM = 1.9891D33
      SOLR = 6.9598D10
      SOLL = 3.8418D33
C SOLAR ATMOSPHERIC PRESSURE, CONVECTIVE OVERTURN
C TIMESCALE (Local Value - Hp(BASE)/Velocity 1 Hp above base
C Note that a global integral of dr/v would be 3 times larger
C Across the board Demarque & Kim 1996)
      SOLP = 10**4.93456428
      SOLTAU = 9.40730218D5
C Solar Equatorial Rotation Rate
C      SOLW = 2*CPI/2.54D1/CSECDAY
C READ IN LIST OF FILE NAMES AND NUMBER OF TRACKS
      OPEN(UNIT=11,STATUS='OLD')
      READ(UNIT=11,NML=CONTROL)
      CLOSE(UNIT=11)
C      READ(11,10)INUMT,LSOLID,IWIND,FK,PMMA,PMMB,
C     *     PMMC,PMMM,SOLJDOT,SOLMDOT,PDISK,TDISK,TAUCOUPLE
      WRITE(*,10)INUMT,LSOLID,IWIND,FK,PMMA,PMMB,
     *     PMMC,PMMM,SOLJDOT,SOLMDOT,PDISK0(1),TDISK0(1),
     *     TAUCOUPLE,WCRIT,LROSS,LJTOM
 10   FORMAT('NUMBER OF TRACKS',I4,' SOLID BODY ROTATION',L2,
     * ' WIND LAW TYPE',I4,' TORQUE SCALING FACTOR',F8.4/
     * 'PMM A (MDOT EXP)',F8.4,' PMM B (B EXP)',F8.4,
     * ' PMM C (B*R^C~CONST)',F8.4,' PMM M',F8.4/
     * 'SOLAR JDOT',1PE12.4,' SOLAR MDOT',E12.4/
     * 'STARTING PROT',0PF8.4,' TAU DISK',F8.4,' TAU COUPLE',1PE12.4/
     * 'SATURATION THRESHOLD',E12.4,' SCALED BY TAU CZ',L2,
     * 'USED CONSTANT JTOM',L2)
C FOR SOLAR CALIBRATION, REQUIRE ONLY 1 INPUT TRACK
      IF(LCALSOL.AND.INUMT.GT.1)THEN
      WRITE(*,7)INUMT
 7       FORMAT('SOLAR CALIBRATION REQUIRES 1 TRACK ',
     *       I5,' SELECTED. RESET INUMT TO 1 AND RERUN')
         STOP
      ENDIF
C ECHO RESULTS, TRAP OUT PATHOLOGIES
      II = 12
      IMAX = II + INUMT
      DO J = 1,INUMT
         JJ = II + J
         OPEN(UNIT=JJ,STATUS='OLD')
         K = 1
         READ(JJ,15)SAGE(J,K),SLL,SRL,STEFF(J,K),
     *      SMCZ(J,K),SRCZ(J,K),SXC(J,K),SI(J,K),SIE(J,K),
     *      STAUCZ(J,K),SHEC(J,K),SPL,SM(J,K)
 15       FORMAT(9/,17X,1P3E16.8,16X,1P1E16.8,16X,1P1E16.8,
     *           1P1E12.4,128X,1P1E16.8,
     *           696X,1P2E16.8,64X,1P2E16.8,80X,1P2E16.8)
            SL(J,K)=10.0D0**SLL
            SP(J,K)=10.0D0**SPL
            SR(J,K)=10.0D0**SRL
            SIC(J,K) = SI(J,K)-SIE(J,K)
C         WRITE(*,911)SAGE(J,K),SL(J,K),SR(J,K),STEFF(J,K),
C     *      SMCZ(J,K),SRCZ(J,K),SXC(J,K),SI(J,K),SIE(J,K),
C     *      STAUCZ(J,K),SHEC(J,K),SP(J,K),SM(J,K)
C 911     FORMAT(1P13E16.8)
         DO K = 2,NMOD
            READ(JJ,20,END=30)SAGE(J,K),SLL,SRL,STEFF(J,K),
     *      SMCZ(J,K),SRCZ(J,K),SXC(J,K),SI(J,K),SIE(J,K),
     *      STAUCZ(J,K),SHEC(J,K),SPL,SM(J,K)
            SL(J,K)=10.0D0**SLL
            SP(J,K)=10.0D0**SPL
            SR(J,K)=10.0D0**SRL
            SIC(J,K) = SI(J,K)-SIE(J,K)
 20         FORMAT(17X,1P3E16.8,16X,1P1E16.8,16X,1P1E16.8,
     *           1P1E12.4,128X,1P1E16.8,
     *           696X,1P2E16.8,64X,1P2E16.8,80X,1P2E16.8)
         END DO
 30      CONTINUE
         NM(J)=K-1
      END DO
C SET UP CONSTANTS AND PRODUCTS OF STRUCTURE VARIABLES USED IN THE 
C ANGULAR MOMENTUM LOSS LAW IF ANGULAR MOMENTUM LOSS IS INCLUDED
      IF(IWIND.NE.1)THEN
         CALL SETUP(INUMT,NM,SAGE,SM,SMCZ,SP,SR,SRCZ,
     *                 SL,EXCEN,EXW,FSTRUCT,FCZ,FCEN,FK2)
      ENDIF
      DO III=1,NUMROT
         IOUT = 59+III
         SJTOM = SJ0(III)
         PDISK = PDISK0(III)
         TDISK = TDISK0(III)
C MHP 9/13 ADDED CZ MASS TO CALL TO CHECK FOR RADIATIVE ENVELOPES
         IF(LSOLID)THEN
            CALL SOLIDEVOL(INUMT,NM,SAGE,SI,STAUCZ,EXCEN,EXW,
     *                  FCEN,FK2,FSTRUCT,SWE,SJ,SPROT,SMCZ,SM)
         ELSE
            CALL DREVOL(INUMT,NM,SAGE,SI,SIE,SIC,STAUCZ,EXCEN,EXW,
     *     SRCZ,SMCZ,FCEN,FK2,FSTRUCT,FCZ,SWC,SWE,SJ,SJC,SJE,SPROT)
         ENDIF
C CALL SR WITH APPROPRIATE ANGULAR MOMENTUM LOSS MODEL
C      IF(IWIND.EQ.1)THEN
C NO ANGULAR MOMENTUM LOSS
C         CALL CONSERVE(INUMT,NM,SAGE,SI,SIE,SIC,SMCZ,SRCZ,SWC,
C     *                 SWE,SJ,SJC,SJE,SPROT)
C      ELSE IF(IWIND.EQ.2)THEN
C SCALED KAWALER (1988) WIND LAW, WITH A SATURATION
C THRESHOLD WCRIT AND AN OPTION TO SCALE IT WITH ROSSBY NUMBER LROSS
C        CALL KWIND(INUMT,NM,SAGE,SI,SIE,SIC,SM,SMCZ,SR,SRCZ,STAUCZ,
C     *             SWC,SWE,SJ,SJC,SJE,SPROT)
C     ELSE IF(IWIND.EQ.3)THEN
C PINSONNEAULT ET AL. 2012 WIND LAW, WITH A SATURATION THRESHOLD
C STRUCTURED IN THE SAME WAY AS THE KAWALER LAW.
C        CALL PWIND
C      ELSE IF(IWIND.EQ.4)THEN
C      ENDIF
C OUTPUT DATA
         OPEN(UNIT=IOUT,STATUS='UNKNOWN')
         WRITE(IOUT,93) INUMT
 93      FORMAT(' NUMBER OF TRACKS',I4,' FOLLOWING LINES INCLUDE NUMBER'
     *   ,' OF MODELS PER TRACK, STARTING MASS, AND STARTING ROTATION',
     *   ' PERIOD')
         WRITE(IOUT,95)(J,NM(J),SM(J,1),SPROT(J,1),J=1,INUMT)
 95      FORMAT(2I5,2F8.4)
         WRITE(IOUT,90)
 90      FORMAT(2X,'J',4X,'K',4X,'Age(Gyr)',9X,'L/Lsun',10X,'R/Rsun',
     *       7X,' LogTeff(K)',
     *       7X,'Mcz(Msun)',8X,'Rcz(Rsun)',10X,'Xcen',9X,'Itot(cgs)',
     *       7X,'Icz(cgs)',6X,'Tau(cz)(sec)',3X,'HeCore(Msun)',5X,
     *       'Patm(cgs)',7X,'Mass(Msun)',6x,'Prot(days)',6x,
     *       'Icore(cgs)',5x,'Omega(core)',5x,'Omega(env)',6x,
     *       'Jtot(cgs)',6x,'Jcore(cgs)',6x,'Jenv(cgs)',2x,
     *       'CentrifugalCorr',5x,'CoronalB/Bsol',7x,
     *       'dM/dt(Msun/yr)')
         FAC_CEN = 0.0D0
         B_BSOL = 0.0D0
         DMDT_DMDTSOL = 0.0D0
         DMDT = 0.0D0
         IF(IWIND.EQ.3)THEN
            IF(WCRIT.GT.0.0D0)THEN
               BMAX = (WCRIT/SOLW)**PMMB
               DMDTMAX = (WCRIT/SOLW)**PMMA
            ELSE
               BMAX = 9.99D9
               DMDTMAX = 9.99D9
            ENDIF
         ENDIF
         DO J = 1,INUMT
            DO K = 1,NM(J)
C LOSS LAW INGREDIENTS
               IF(IWIND.EQ.3 .AND. SWE(J,K).GT.0.0D0 .AND. 
     *            STAUCZ(J,K).GT.0.0D0)THEN
                  FAC_CEN=(FK2/(FK2**2+SWE(J,K)**2*FCEN(J,K))
     *                    **0.5D0)**EXCEN
                  B_BSOL=MIN(BMAX,
     *                   (SWE(J,K)*STAUCZ(J,K)/SOLW/SOLTAU)**PMMB)
                  B_BSOL=B_BSOL*(SP(J,K)/SOLP)**0.5D0/SR(J,K)**PMMC
                  DMDT = MIN(DMDTMAX,(SWE(J,K)*STAUCZ(J,K)/
     *                        SOLW/SOLTAU)**PMMA)
                  DMDT = DMDT*SOLMDOT*CSECYR/SOLM*SL(J,K)
               ENDIF
               WRITE(IOUT,100)J,K,SAGE(J,K),SL(J,K),SR(J,K),STEFF(J,K),
     *         SMCZ(J,K),SRCZ(J,K),SXC(J,K),SI(J,K),SIE(J,K),
     *         STAUCZ(J,K),SHEC(J,K),SP(J,K),SM(J,K),SPROT(J,K),
     *         SIC(J,K),SWC(J,K),SWE(J,K),SJ(J,K),SJC(J,K),SJE(J,K),
     *         FAC_CEN,B_BSOL,DMDT
 100           FORMAT(I4, 4X, I4, 4X, 1P23E16.8)
            END DO
         END DO
      END DO
      STOP
      END
     
