C ANGULAR MOMENTUM EVOLUTION UNDER THE ASSUMPTION OF THE SILLS ET AL. 2000 JDOT
      SUBROUTINE SETUP(INUMT,NM,SAGE,SM,SMCZ,SP,SR,SRCZ,
     *                 SL,EXCEN,EXW,FSTRUCT,FCZ,FCEN,FK2)
      IMPLICIT REAL*8 (A-H, O-Z)
      IMPLICIT LOGICAL*4 (L)
      PARAMETER(NTRACK=40,NMOD=20000)
C USER PARAMETERS, WIND LAW
      COMMON/PARAM/LSOLID,IWIND,PMMA,PMMB,PMMC,PMMM,SOLJDOT,SOLMDOT,FK,
     *             PDISK,TDISK,TAUCOUPLE,WCRIT,LROSS
C SOLAR UNITS IN CGS, USED FOR LOSS LAW
C SOLAR MASS, RADIUS, LUMINOSITY, SURFACE P, OVERTURN TIMESCALE (CGS),
C ANGULAR VELOCITY(RAD/S)
      COMMON/SOLAR/ SOLM,SOLR,SOLL,SOLP,SOLTAU,SOLW
C PHYSICAL CONSTANTS
C G (CGS), 2/3, SECONDS IN YEAR, SECONDS IN DAY
      COMMON/CONST/CG,CC23,CPI,CSECYR,CSECDAY
C INPUTS FROM TRACKS - CGS OR SOLAR UNITS AS NOTED
C SAGE = AGE (YR), SL = L/LSUN SR = R/RSUN SM = M/MSUN
C SRCZ = R OF CZ BASE (CGS) SMCZ = MASS OF SURFACE CZ, MSUN
C SP = ATM PRESSURE TAU=2/3
      REAL*8 SAGE(NTRACK,NMOD),SM(NTRACK,NMOD),SR(NTRACK,NMOD),
     *       SL(NTRACK,NMOD),SMCZ(NTRACK,NMOD),SRCZ(NTRACK,NMOD),
     *       SP(NTRACK,NMOD)
C EXPONENTS FOR FACTORS IN LOSS LAW
      REAL*8 EXCEN,EXR,EXM,EXP,EXL,EXW
C SPLINE INTERPOLATION VECTORS
      REAL*8 YDMDT(NMOD),XMID(NMOD),DMCZDT(NMOD)
C NM = VECTOR OF TRACK LENGTHS
      INTEGER*4 IWIND,NM(NTRACK)
C OUTPUT VECTORS - CGS UNITS
C LOSS LAW HAS THE FORM JDOT=FSTRUCT*F(OMEGA) AND
C FOR 2-ZONE MODELS THE MATERIAL THAT MOVES FROM
C CORE TO ENVELOPE, OR VICE VERSE, MUST BE ACCOUNTED
C FOR VIA A TERM FCZ = 2/3RCZ^2*DMCZ/DT
      REAL*8 FWIND,FSTRUCT(NTRACK,NMOD),FCZ(NTRACK,NMOD),
     *       FCEN(NTRACK,NMOD)
      SAVE
C CONSTANT TERM FOR CENTRIFUGAL TORQUE SUPPRESSION - SEE MATT ET AL. 2012
      FK2 = 0.056D0
      DO I = 1,INUMT
         DO J = 1,NM(I)
            FCEN(I,J) = 0.5D0*(SOLR**3/SOLM/CG)*
     *                  SR(I,J)**3/SM(I,J)
         END DO
      END DO
      IF(IWIND.EQ.2)THEN
C LOSS LAW CONSTANT FOR KAWALER LAW (N=1.5)
	 FWIND = FK*2.036D33*1.452D9**1.5D0*1.0D9*CSECYR
C SET UP INDICES FOR LOSS LAW IN KAWALER LAW
C EXR = EXPONENT FOR R
C EXM = EXPONENT FOR M
C EXW = EXPONENT FOR OMEGA
         EXCEN = 0.0D0
         EXR = 0.5D0
         EXM = -0.5D0
         EXPR = 0.0D0
         EXL = 0.0D0
         EXW = 3.0D0
      ELSE IF(IWIND.EQ.3)THEN
C SET UP INDICES FOR LOSS LAW IN TERMS OF PMM A, B, C,
C EXCEN = EXPONENT FOR CENTRIFUGAL TERM, 1/(K2^2+W^2 R^3/GM)^PMMM/2
         EXCEN = PMMM
         EXR = 2.0D0+5.0D0*PMMM-4.0D0*PMMM*PMMC
         EXM = -PMMM
C EXL = EXPONENT FOR L;ASSUME LX~LBOL
C EXP = EXPONENT FOR P;ASSUME EQUIPARTITION FOR SPOT FIELDS P~B^2
         EXPR = 2.0D0*PMMM
         EXL = 1.0D0 - 2.0D0*PMMM
         EXW = 1.0D0+PMMA*(1.0D0 - 2.0D0*PMMM)+4.0D0*PMMM*PMMB
C LOSS LAW CONSTANT FOR PMM LAW
         FWIND = FK*SOLJDOT*1.0D9*CSECYR/SOLW**EXW
      ENDIF
C PRODUCT OF STRUCTURAL FACTORS USED FOR THE ANGULAR MOMENTUM LOSS LAW.
      DO I = 1,INUMT
         DO J = 1,NM(I)
            FSTRUCT(I,J)=FWIND*(SR(I,J)**EXR)*(SM(I,J)**EXM)*
     *                   ((SP(I,J)/SOLP)**EXPR)*(SL(I,J)**EXL)
         END DO
      END DO
C CORE-ENVELOPE DECOUPLING IS TREATED IN A 2-ZONE MODEL, WHERE THE TRANSFER OF
C ANGULAR MOMENTUM BETWEEN THE TWO IS TREATED AS
C DELTA J = OMEGA(SOURCE)*2/3*R_CZ**2*DM_CZ/DT * DELTA (TIME)
C WE THEREFORE NEED THE STRUCTURAL PRODUCT OF THE RADIUS AT THE CZ BASE
C AND THE RATE OF CHANGE OF THE SURFACE CONVECTION ZONE DEPTH, WHICH ARE DEFINED
C AT THE START AND MIDDLE OF THE TIMESTEP RESPECTIVELY.  WE THEREFORE 
      IF(.NOT.LSOLID)THEN
C 2/3 R_CZ**2
         DO I = 1,INUMT
            DO J = 1,NM(I)
               FCZ(I,J)=CC23*(SOLR*SRCZ(I,J))**2
            END DO
         END DO
C D M_CZ/DT
         DO I = 1,INUMT
            JJJ = NM(I)
            DO J = 1,JJJ
               XMID(J) = SAGE(I,J)
               DMCZDT(J) = SMCZ(I,J)*SOLM
            END DO
C SPLINE FACTORS FOR MOMENT OF INERTIA
            CALL SPLINC(XMID,DMCZDT,YDMDT,JJJ)
            DO J = 1,JJJ-1
C FIRST DERIVATIVE AT A POINT IS
C DY/DX(I) = (Y(I+1)-Y(I))/(X(I+1)-X(I))+
C 1/3(X(I+1)-X(I))*Y2A(I)-1/6(X(I+1)-X(I))*Y2A(I+1)
C WHERE Y2A IS THE SECOND DERIVATIVE IN SPLINC (C.F. NUMERICAL RECIPES 3.3)
               H = XMID(J+1)-XMID(J)
               FM=(DMCZDT(J+1)-DMCZDT(J))/H+
     *             H*YDMDT(J)/3.0D0-H*YDMDT(J+1)/6.0D0
               FCZ(I,J)=FM*FCZ(I,J)
            END DO
C FLIP INDICES FOR FINAL POINT
            H = XMID(JJJ)-XMID(JJJ-1)
            FM=(DMCZDT(JJJ)-DMCZDT(JJJ-1))/H-
     *          H*YDMDT(JJJ-1)/6.0D0+H*YDMDT(JJJ)/3.0D0
            FCZ(I,JJJ)=FM*FCZ(I,JJJ)
         END DO
      ENDIF
      RETURN
      END

