#!/bin/bash

# This script removes the test files generated by run_tests.sh.
# Usage: ./clear_tests.sh
# KC 2025-04-18

while IFS= read -r line; do
  if [[ -z "$line" || "$line" =~ ^# ]]; then
    continue
  fi

  read dir test <<< "$line"
  echo "Removing test $test in directory $dir"

  for file in "$dir"/*/"$test".*; do
    rm "$file"
  done
done < "testsuite.sh"