C
C
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C ENTIME
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      SUBROUTINE ENTIME(DELTS,HL,HP,HR,HT,TEFFL,M,EDELT)

      PARAMETER(JSON=5000)
      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)

      COMMON/CONST/CLSUN,CLSUNL,CLNSUN,CMSUN,CMSUNL,CRSUN,CRSUNL,CMBOL
      COMMON/CONST1/ CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
      COMMON/CONST3/CDELRL,CMIXL,CMIXL2,CMIXL3,CLNDP,CSECYR
      COMMON/CTLIM/ATIME(14),TCUT(5),TSCUT,TENV0,TENV1,TENV,TGCUT
      COMMON/OLDMOD/HPO(JSON),HTO(JSON),HRO(JSON),HLO(JSON),HDO(JSON),
     *              HCOMPP(15,JSON),HSS(JSON),LCO(JSON),LCZO(JSON),TEFFLO
      COMMON/CENV/TRIDT,TRIDL,SENV0,LSENV0,LNEW0
      DIMENSION HT(JSON),HL(JSON),HP(JSON),HR(JSON)
      DIMENSION NHMAX(4),HMAX(4)
      SAVE

C  THIS SR LIMITS THE TIMESTEP BASED ON THE REQUIREMENT THAT THE CHANGES FROM
C  ONE MODEL TO THE NEXT IN T,AND L BE LESS THAN THE SIZE OF THE ENVELOPE TRIANGLE
C  (TRIL AND TRIT). THIS PREVENTS EXTRAPOLATION OUTSIDE OF THE TRIANGLE 
C  FOR SMALL ENVELOPE TRIANGLES.
C
C INPUT VARIABLES
C DECLARED VARIABLES :
C   DELTS : PREVIOUS MODEL TIMESTEP.
C   HL : RUN OF LUMINOSITY(AS A FUNCTION OF MASS) IN THE CURRENT MODEL.
C   HP : RUN OF PRESSURE IN THE CURRENT MODEL.
C   HR : RUN OF RADIUS IN THE CURRENT MODEL.
C   HT : RUN OF TEMPERATURE IN THE CURRENT MODEL.
C   M : NUMBER OF POINTS IN THE MODEL.
C VARIABLES IN COMMON BLOCKS :
C   TRIL: DELT L OF ENVELOPE TRIANGLE
C   TRIT: DELT T OF ENVELOPE TRIANGLE
C   ATIME(12): maximum percentage change in the timestep from the previous one
C   HLO : RUN OF LUMINOSITY(AS A FUNCTION OF MASS) IN THE PREVIOUS MODEL.
C   HPO : RUN OF PRESSURE IN THE PREVIOUS MODEL.
C   HRO : RUN OF RADIUS IN THE PREVIOUS MODEL.
C   HTO : RUN OF TEMPERATURE IN THE PREVIOUS MODEL.
C
C OUTPUT VARIABLES :
C   EDELT : TIME STEP FOR REQUESTED CHANGE IN P,T,R,L.
C
C FIND MAXIMUM ABSOLUTE TIME DIFFERENCES FOR EACH QUANTITY
C
C	PRINT*,'FOR TEFF', TEFFLO, TEFFL, TRIDT
C	PRINT*,'FOR LUM', HLO(M), HL(M), TRIDL
C  TEMPERATURE
      HMAX(1)=TRIDT
C  LUMINSOITY
	HMAX(2)=TRIDL

	 TESTT = ABS(TEFFLO-TEFFL)
		 !IF(HMAX(1).LE.TESTT) HMAX(1) = TESTT
C FIND LAST POINT IN PREVIOUS MODEL
	 DO I=1,JSON-1
		IF(HLO(I) .NE. 0.0 .AND. HLO(I+1) .EQ. 0.0) THEN
			MO = I
			GOTO 123
		ENDIF
	ENDDO
  123 CONTINUE

	 DO I=1,JSON-1
		IF(HL(I) .NE. 0.0 .AND. HL(I+1) .EQ. 0.0) THEN
			MN = I
			GOTO 124
		ENDIF
	ENDDO
  124 CONTINUE



	 PRINT*, M,MN,MO	
	 TESTL = ABS(HLO(MO)-HL(MN)) 
		 !IF(HMAX(2).LE.TESTL) HMAX(2) = TESTL
	PRINT*, 'TESTL, TRIDL', TESTL, TRIDL
	PRINT*, 'TESTT, TRIDT', TESTT, TRIDT
C NOW ACTUALLY LIMIT THE TIMESTEP BY A FACTOR THAT REDUCES THE
C TIME CHANGES IN ALL QUANTITIES TO THE PS VALUES OR LESS
      !FAC = HMAX(1)/TRIDT
	! 08/2014 FAC = TESTT/TRIDT
	FAC = TRIDT/TESTT
      !IF (HMAX(2)/TRIDL.GT.FAC) FAC=HMAX(2)/TRIDL
	! 08/14 IF (TESTL/TRIDL.GT.FAC) FAC=TESTL/TRIDL
	IF (TRIDL/TESTL.LT.FAC) FAC=TRIDL/TESTL
	PRINT*, 'FAC = ', FAC
C  IF NO CHANGE FROM PREVIOUS MODEL,SET PDELT TO TIMESTEP
C  STORED IN THE PREVIOUS MODEL.
      IF (FAC.EQ.0.D0) FAC=1.0D0
C RESTRICT CHANGE IN TIMESTEP TO NO MORE THAN A FACTOR OF ATIME(12)% 
C UP OR DOWN.
      !TEMP=1.0D0+ATIME(12)
	!PRINT*, TEMP
      !IF (FAC.GT.1.0+ATIME(12)) FAC=1.0+ATIME(12)
      !IF (FAC.LT.1.0-ATIME(12)) FAC=1.0-ATIME(12)
	!IF (FAC0 .NE. FAC) PRINT*, 'fac altered'
      !EDELT = DELTS/FAC
	EDELT = DELTS*FAC
	PRINT*, EDELT
      RETURN
      END
