CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                               GETSPOT                             C
C                           A.Ash 7/26                              C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE GETSPOT(HCOMP,HR,HP,HD,HS1,HT,FP,FT,TEFFL,HSTOT,BL,M,
     *                  LC,RBCZ, OMEGA)
C     *                  LC,RBCZ, OMEGA, TAUCZ)
      IMPLICIT REAL*8(A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      PARAMETER (JSON=5000)
      COMMON/LUOUT/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,IOWR
      COMMON/ENVGEN/ATMSTP,ENVSTP,LENVG
      COMMON/INTATM/ATMERR,ATMD0,ATMBEG,ATMMIN,ATMMAX
      COMMON/INTENV/ENVERR,ENVBEG,ENVMIN,ENVMAX
      COMMON/CONST1/CLN,CLNI,C4PI,C4PIL,C4PI3L,CC13,CC23,CPI
      COMMON/CONST/CLSUN,CLSUNL,CLNSUN,CMSUN,CMSUNL,CRSUN,CRSUNL,CMBOL
      COMMON/CONST2/CGAS,CA3,CA3L,CSIG,CSIGL,CGL,CMKH,CMKHN
C KC 2025-05-30 reordered common block elements
C JvS 08/25 Updated with new elements
      COMMON/ENVSTRUCT/ENVP(JSON),ENVT(JSON),ENVS(JSON),ENVD(JSON),
     *     ENVR(JSON),ENVX(JSON),ENVZ(JSON),LCENV(JSON),
     *     EDELS(3,JSON),EVELS(JSON),EBETAS(JSON),
     *     EGAM1(JSON),EQCP(JSON),EFXIONS(3,JSON),
     *     ENVO(JSON), ENVL(JSON),EQDT(JSON),NUMENV
      COMMON/SCRTCH/SESUM(JSON),SEG(7,JSON),SBETA(JSON),SETA(JSON),
     * LOCONS(JSON),SO(JSON),SDEL(3,JSON),SFXION(3,JSON),SVEL(JSON),SCP(JSON)
C       DIMENSION HCOMP(15,JSON),HR(JSON),HP(JSON),HD(JSON),HG(JSON),HS1(JSON),  ! KC 2025-05-31
      DIMENSION HCOMP(15,JSON),HR(JSON),HP(JSON),HD(JSON),HS1(JSON),
     *      HT(JSON),FP(JSON),FT(JSON),HCOMPF(15,JSON),HRF(JSON),HPF(JSON),
     *      HDF(JSON),HSF(JSON),HTF(JSON),LC(JSON),HGF(JSON),HVF(JSON),
     *  DELF1(JSON),DELF2(JSON),LCF(JSON)
      REAL*8 DUM1(4),DUM2(3),DUM3(3),DUM4(3)
      INTEGER*4 KATM, KENV, KSAHA

      COMMON/OVRTRN/LNEWTCZ,LCALCENV,TAUCZ,TAUCZ0,PPHOT,PPHOT0,FRACSTEP

      COMMON/SPOTS/SPOTF,SPOTX,LSDEPTH
C G Ash 7/27, Add spot common block
      COMMON/SPOTEVOL/EVOLSPOTS,SPOTEX,SPOTF_SUN, SPOTMAX, RO_SAT
      LOGICAL EVOLSPOTS
C G Ash END
      COMMON/PMMWIND/PMMA,PMMB,PMMC,PMMD,PMMM,PMMJD,PMMMD,PMMSOLP,PMMSOLW,
     *                PMMSOLTAU,LMWIND,LROSSBY,LBSCALE,AWIND
      COMMON/CWIND/WMAX,EXMD,EXW,EXTAU,EXR,EXM,EXL,EXPR,CONSTFACTOR,
     *             STRUCTFACTOR,EXCEN,C_2,LJDOT0

      DIMENSION HL(JSON),
     * TRIT(3),TRIL(3),PS(3),TS(3),RS(3),
     * CFENV(9),TLUMX(8),OMEGA(JSON)

      COMMON/ROT/WNEW,WALPCZ,ACFPFT,ITFP1,ITFP2,LROT,LINSTB,LWNEW
      COMMON/DISK/SAGE,TDISK,PDISK,LDISK

      INTEGER TESTVALUE
      COMMON/TESTING/TESTVALUE

        SAVE

C          WRITE(*,999) TESTVALUE
C999       FORMAT("TESTVALUE=",I4)

      IF(M.EQ.0)THEN
C          WRITE(*,201) TAUCZ
C201       FORMAT("TAU",1PE12.3)

          RO_STAR = (2*3.14159)/(PDISK*TAUCZ)

            SPOTF = ((RO_SAT/MAX(RO_STAR,RO_SAT))**(SPOTEX))
            SPOTF = SPOTF * SPOTMAX


      ELSE
        RO_STAR = (2*3.14159)/(OMEGA(M)*TAUCZ)

        SPOTF = ((RO_SAT/MAX(RO_STAR,RO_SAT))**(SPOTEX))
        SPOTF = SPOTF * SPOTMAX


      ENDIF
C      WRITE(*,201) PPHOT
C      WRITE(*,202) PMMSOLP
C      WRITE(*,203) OMEGA(M)
C      WRITE(*,204) WMAX
C      WRITE(*,205) TAUCZ
C      WRITE(*,206) PMMSOLW
C      WRITE(*,207) PMMSOLTAU
C      WRITE(*,208) SPOTEX
C      WRITE(*,209) SPOTF

C201   FORMAT("PPHOT",1P1E12.3)
C202   FORMAT("PMMSOLP", 1P1E12.3)
C203   FORMAT("OMEGA", 1P1E10.4)
C204   FORMAT("WSAT", 1P1E10.4)
C205   FORMAT("TAUCZ",1P1E12.3)
C206   FORMAT("SOLW",1P1E12.3)
C207   FORMAT("SOLTAUCZ",1P1E12.3)
C208   FORMAT("SPOTEX",1P1E12.3)
C209   FORMAT("FSPOT",1P1E12.3)
      RETURN
      END

