C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     READ PURE Z LAOL89
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE RDZLAOL(FPUREZ)
C MHP 10/02 vector v not used
C      SUBROUTINE RDZLAOL(V)

      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      REAL*8 DUMMY(104)
      CHARACTER*256 FPUREZ

C MHP 8/25 Removed character file names from common block
C DBG 12/95 ARRAYS FOR PURE Z TABLE
      COMMON/ZLAOL/ZOLAOL(104,52), ZOT(52), ZORHO(104),
     *  NUMRHOZ, NUMTZ
C 9/25/26 MHP via Claude
C code changed to consolidate all I/O logical unit numbers, previously
C scattered across COMMON/LUOUT/, COMMON/LUNUM/, COMMON/ALEX06/,
C COMMON/ACDPTH/, COMMON/NEWOPAC/, COMMON/LOPAL95/, COMMON/ATMOS2/,
C COMMON/ALATM03/, COMMON/OPALEOS/, and COMMON/SCV2/, into a single
C COMMON/IOUNITS/
      COMMON/IOUNITS/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,
     *  IOWR,IFIRST,IRUN,ISTAND,IFERMI,IOPMOD,IOPENV,IOPATM,ISNU,
     *  IALEX06,ICLCD,IJLAST,IOPUREZ,IcondOpacP,ILIV95,IOATM,IOATMA,
     *  IOPALE,ISCVH,ISCVHE,ISCVZ
C OPACITY COMMON BLOCKS - modified 3/09
C 9/23/26 MHP via Claude
C code changed to remove the OPAL92 opacity tables
C 9/23/26 MHP via Claude
C code changed to remove the Kurucz 1990 opacity tables
C 9/23/26 MHP via Claude
C code changed to remove the LAOL89 opacity tables
C 9/24/26 MHP via Claude
C code changed to remove the Alexander 1995 opacity tables
C 9/24/26 MHP via Claude
C code changed to remove dead opacity-table Z-value inputs
C 9/24/26 MHP via Claude
C code changed to merge COMMON /MISCOPAC/ and COMMON/NWLAOL/ into
C COMMON /NEWOPAC/
      COMMON/NEWOPAC/ZOPAL951,TMOLMIN,TMOLMAX,TOLLAOL,LALEX06,LOPAL95,
     *  L2Z,LLAOL,LPUREZ,LcondOpacP
C      DIMENSION V(12)
      SAVE

      OPEN(UNIT=IOPUREZ, FILE=FPUREZ,FORM='FORMATTED',
     *        STATUS='OLD')
C     READ IN ARRAY SIZES
      READ(IOPUREZ,100)N,NUMRHOZ,NUMTZ
  100 FORMAT(/,18X,I2,9X,I3,14X,I3)
      IF(N.NE.1.OR.NUMRHOZ.GT.104.OR.NUMTZ.GT.52) THEN
         WRITE(ISHORT,*)' Z OPACITY INPUT ERROR.'
         STOP
      END IF
      READ(IOPUREZ,120)(DUMMY(I),I=1,11)
  120 FORMAT(47X,F8.5,//,1P6E12.5,/,1P4E12.5)
      READ(IOPUREZ,131)DUMMY(1)
  131 FORMAT(54X,F8.5,///////)
C     READ IN H MASS FRACTIONS OF TABLE
      READ(IOPUREZ,140)DUMMY(1)
  140 FORMAT(/,(1P6E12.5))
C     READ IN DENSITY GRID OF TABLE
      READ(IOPUREZ,150)(ZORHO(II),II=1,NUMRHOZ)
  150 FORMAT(/,(1P6E12.5))
C     READ IN TEMPERATURE GRID OF TABLE
      READ(IOPUREZ,160)(ZOT(II),II=1,NUMTZ)
  160 FORMAT(/,(1P6E12.5))
C     READ IN PURE Z OPACITIES
      READ(IOPUREZ,170)
  170 FORMAT(1X)
      DO IR=1,NUMRHOZ
         READ(IOPUREZ,200)
  200    FORMAT(1X)
         READ(IOPUREZ,210)(ZOLAOL(IR,IT),IT=1,NUMTZ)
  210    FORMAT(1P6E12.5)
         END DO
      CLOSE(IOPUREZ)

      RETURN
      END
