C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     SETUPOPAC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE SETUPOPAC(XENV, V)
      use settings, only : LDIFZ  ! /GRAVS3/
      use tables, only : LPUREZ  ! /NWLAOL/
      use settings, only : LZRAMP  ! /ZRAMP/
      use settings, only : LALEX06, LLAOL89, LOPAL92, LOPAL95, LKUR90, LALEX95, L2Z  ! /NEWOPAC/

      IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT LOGICAL*4(L)
      DIMENSION V(12)
      SAVE

C
C     THIS SUBROUTINE READS IN SPECIFIED OPACITY TABLES AND
C     SET UP SPLINES FOR THE TABLES.
C     WHEN LZRAMP=T OR LDIFZ=T THEN READ IN SECOND SET OF
C     OPACITY TABLES AT DIFFERENT Z (E.G. ZOPAL952).
      L2Z = LZRAMP.OR.LDIFZ
C
C     INTERIOR TABLES
C
C     READ IN OPAL95 TABLES
      IF (LOPAL95) THEN
        CALL LL95TBL
      CALL OP95XTAB(XENV)
      END IF

C     READ IN OPAL92 TABLES AT ZOPAL1 AND ZOPAL2
      IF (LOPAL92) THEN
         CALL SETLLO
       CALL LL4TH(XENV)
      END IF
C     READ IN LAOL89 TABLES AT ZLAOL1 AND ZLAOL2
      IF (LLAOL89) THEN
         CALL RDLAOL(V)
       CALL SULAOL
      END IF
C
C     READ IN LAOL89 PURE Z TABLE
C
      IF(LPUREZ)THEN
         CALL RDZLAOL
       CALL ZSULAOL
      END IF
C
C     LOW TEMP TABLES
C
C     READ IN ALEX 2006 TABLES
      IF (LALEX06) THEN
        CALL READALEX06
C     READ IN ALEX 1995 TABLES
      ELSE IF (LALEX95) THEN
        CALL ALXTBL
      CALL ALX8TH(XENV)
C     READ IN KURUCZ TABLE AT ZKUR1 AND ZKUR2
      ELSE IF (LKUR90) THEN
          CALL SETKRZ
      END IF
      RETURN
      END
