C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C SUBROUTINE SPLINT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C REAL*4 VERSION FOR OPACITIES CHANGED TO REAL*8 10/02 MHP
C TAKEN FROM NUMERICAL RECIPES, PRESS, ET AL, P89.
C GIVEN THE ARRAYS XA AND YA OF LENGTH N, WHICH TABULATE A FUNCTION
C (WITH THE XA[I]'S IN ORDER), AND GIVEN THE ARRAY Y2A, WHICH IS THE
C OUTPUT OF SPLINE ABOVE, AND GIVEN A VALUE OF X, THIS ROUTINE RETURNS
C A CUBIC-SPLINE INTERPOLATED VALUE Y.
      SUBROUTINE SPLINT(XA, YA, N, Y2A, X, Y, KLO, KHI)
      IMPLICIT REAL*8 (A-H,O-Z)
C      IMPLICIT REAL*4 (A-H,O-Z)
C 9/25/26 MHP via Claude
C code changed to consolidate all I/O logical unit numbers, previously
C scattered across COMMON/LUOUT/, COMMON/LUNUM/, COMMON/ALEX06/,
C COMMON/ACDPTH/, COMMON/NEWOPAC/, COMMON/LOPAL95/, COMMON/ATMOS2/,
C COMMON/ALATM03/, COMMON/OPALEOS/, and COMMON/SCV2/, into a single
C COMMON/IOUNITS/
      COMMON/IOUNITS/ILAST,IDEBUG,ITRACK,ISHORT,IMILNE,IMODPT,ISTOR,
     *  IOWR,IFIRST,IRUN,ISTAND,IFERMI,IOPMOD,IOPENV,IOPATM,ISNU,
     *  IALEX06,ICLCD,IJLAST,IOPUREZ,IcondOpacP,ILIV95,IOATM,IOATMA,
     *  IOPALE,ISCVH,ISCVHE,ISCVZ
      DIMENSION XA(N), YA(N), Y2A(N)
      SAVE
      KLO = 1
      KHI = N
    1 IF (KHI-KLO .GT. 1) THEN
         K = (KHI+KLO)/2
         IF (XA(K) .GT. X) THEN
            KHI = K
         ELSE
            KLO = K
         END IF
         GOTO 1
      END IF
      H = XA(KHI) - XA(KLO)
      IF (H .EQ. 0D0) THEN
           WRITE(ISHORT,*) 'ERROR IN SPLINT ROUTINE.'
         STOP
      ENDIF
      A = (XA(KHI)-X)/H
      B = (X - XA(KLO))/H
      Y = A*YA(KLO)+B*YA(KHI)+
     1    ((A**3-A)*Y2A(KLO)+(B**3-B)*Y2A(KHI))*(H**2)/6.0D0
      RETURN
      END
